services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    restart: always
    environment:
      MYSQL_DATABASE: task_manager_db
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass123
      MYSQL_ROOT_PASSWORD: rootpass123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Opcional: phpMyAdmin para administrar la DB visualmente
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task-manager-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: taskuser
      PMA_PASSWORD: taskpass123
    depends_on:
      - mysql

volumes:
  mysql_data: